################################################################################
# General
################################################################################

# Top Ranking Group By Request
ranking_count = 20

# Top Slow Requests
slow_count = 37

# Show Standard Deviation column
show_stddev = true

# Show HTTP Status Code columns
show_status_code = true

# Show HTTP Response Bytes columns
show_bytes = true

# Percentiles
percentiles = [ 50.0, 90.0, 95.0, 99.0 ]

################################################################################
# Scale
################################################################################

# for Nginx($request_time)
scale = 0
effective_digit = 3

# for Apache(%D) and Varnishncsa(%D)
#scale = -6
#effective_digit = 6

# for H2O(%{duration}x)
#scale = 0
#effective_digit = 6

# for Envoy
#scale = -3
#effective_digit = 3

# for Rack(Rack::CommonLogger)
#scale = 0
#effective_digit = 4

################################################################################
# Parse
################################################################################

#
# combined + duration
# Nginx example: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time'
# Apache example: "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %D"
# H2O example: "%h %l %u %t \"%r\" %s %b \"%{Referer}i\" \"%{User-agent}i\" %{duration}x"
# Varnishncsa example: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-agent}i" %D'
#
log_format = '^([^ ]+) ([^ ]+) ([^ ]+) \[([^\]]+)\] "((?:\\"|[^"])*)" (\d+) (\d+|-) "((?:\\"|[^"])*)" "((?:\\"|[^"])*)" ([0-9.]+)$'
request_index = 5
status_index = 6
bytes_index = 7
duration_index = 10

#
# Envoy example: use default format
#
#log_format = '^\[([^\]]+)\] "((?:\\"|[^"])*)" (\d+) ([^ ]+) (\d+|-) (\d+|-) (\d+) (\d+) "((?:\\"|[^"])*)" "((?:\\"|[^"])*)" "((?:\\"|[^"])*)" "((?:\\"|[^"])*)" "((?:\\"|[^"])*)"'
#request_index = 2
#status_index = 3
#bytes_index = 6
#duration_index = 7

#
# Rack example: use Rack::CommonLogger, Logger.new("/tmp/app.log")
#
#log_format = '^([^ ]+) ([^ ]+) ([^ ]+) \[([^\]]+)\] "((?:\\"|[^"])*)" (\d+) (\d+|-) ([0-9.]+)$'
#request_index = 5
#status_index = 6
#bytes_index = 7
#duration_index = 8

################################################################################
# Bundle
################################################################################
regexp = '^GET /initialize'
name = 'GET /initialize'
[[bundle]]
regexp = '^GET /login'
name = 'GET /login'
[[bundle]]
regexp = '^POST /login'
name = 'POST /login'
[[bundle]]
regexp = '^GET /register'
name = 'GET /register'
[[bundle]]
regexp = '^POST /register'
name = 'POST /register'
[[bundle]]
regexp = '^GET /logout'
name = 'GET /logout'
[[bundle]]
regexp = '^GET /\ '
name = 'GET /'
[[bundle]]
regexp = '^GET /posts'
name = 'GET /posts'
[[bundle]]
regexp = '^GET /posts/[0-9]+'
name = 'GET /posts/{id}'
[[bundle]]
regexp = '^POST /\ '
name = 'POST /'
[[bundle]]
regexp = '^GET /image/[0-9]+\.*'
name = 'GET /image/{id}.{ext}'
[[bundle]]
regexp = '^POST /comment'
name = 'POST /comment'
[[bundle]]
regexp = '^GET /admin/banned'
name = 'GET /admin/banned'
[[bundle]]
regexp = '^POST /admin/banned'
name = 'POST /admin/banned'
[[bundle]]
regexp = '^GET /@[a-zA-Z]+'
name = 'GET /@{accountName:[a-zA-Z]+}'
[[bundle]]
regexp = '^GET /(css|js|img)/.*'
name = 'GET /(css|js|img)/.*'


#
# You can aggregate requests by regular expression
# For overview of regexp syntax: https://golang.org/pkg/regexp/syntax/
#
#[[bundle]]
#regexp = '^(GET|HEAD) /users/[0-9]+\b'
#name = 'GET /memo/*'
#
#[[bundle]]
#regexp = '^(GET|HEAD) /stylesheets/'
#name = 'GET /stylesheets/*'
#
#[[bundle]]
#regexp = '^(GET|HEAD) /images/'
#name = 'GET /images/*'

################################################################################
# Replace
################################################################################

#
# You can replace the part of urls which matched to your regular expressions.
# For overview of regexp syntax: https://golang.org/pkg/regexp/syntax/
#
#[[replace]]
#regexp = '/[0-9]+(/|\s)'
#replace = '/<num>$1'
#
#[[replace]]
#regexp = '=[0-9]+(&|\s)'
#replace = '=<num>$1'
#
#[[replace]]
#regexp = '\s+HTTP/[0-9.]+$'
#replace = ''

################################################################################